# Generated by Django 4.2.15 on 2024-08-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("CASH", "Наличные"), ("TRANSFER", "Перевод")],
                default="TRANSFER",
                max_length=200,
                verbose_name="Метод оплаты",
            ),
        ),
    ]
