# Generated by Django 4.2.15 on 2024-08-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_lesson_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.TextField(
                help_text="Введите название курса", verbose_name="Название курса"
            ),
        ),
    ]
